[package]
name = "mnist_network_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayfire = "3.8.0"
rand = "0.8.5"
mnist = "0.5.0"
byteorder = "1"
flate2 = "1.0"